### ISSUE TITLE
scheduling.py

### ISSUE THREAD

**Issue by jwei0701** [reed-college/kronos#18]
Need a file that
- [x] 1. refuses to add orals that conflict with personal events;
- [x] 2. refuses to add conflicting orals;
- [x] 3. can print the available time given a user;
- [x] 4. returns possible oral times given four professors' schedule;
- [x] 5. arranges only one oral for each student;
- [x] 6. TBD

**Comment by grantal** [comment]
#1 could be done with [validators](http://docs.sqlalchemy.org/en/latest/orm/mapped_attributes.html) in the models

**Comment by grantal** [comment]
Something like:

``` python
class Event(db.Model):
    ...
    @validates('dtstart', 'dtend')
    def validate_time(self, dtstart, dtend, user, attendees):
        assert user and attendees dont have another event between dtstart and dtend
```

**Comment by jwei0701** [comment]
Gotcha. Thanks!

**Comment by jwei0701** [comment]
Feel like I can never get validators to work. 😿
